'use strict';

const fs = require('node:fs');
const path = require('node:path');

function generateStandaloneTest({ finding, protectedCases, publicControl }) {
  const casesJson = JSON.stringify(protectedCases.map((item) => ({
    id: item.id,
    method: item.method,
    path: item.concrete_path,
    operation: item.operation,
  })), null, 2);
  const publicJson = JSON.stringify({
    id: publicControl.id,
    method: publicControl.method,
    path: publicControl.concrete_path,
  }, null, 2);

  return `/* Generated by BOQA Boundary Regression Compiler. No BOQA runtime dependency. */
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const BASE_URL = requiredEnv('BOUNDARY_BASE_URL').replace(/\\/$/, '');
const OWNER_TOKEN = requiredEnv('BOUNDARY_OWNER_TOKEN');
const OUTSIDER_TOKEN = requiredEnv('BOUNDARY_OUTSIDER_TOKEN');
const PRIVATE_KIND = ${JSON.stringify(finding.expected_private_kind)};
const PRIVATE_MARKER = ${JSON.stringify(finding.expected_private_marker)};
const EXPECTED_OWNER = ${JSON.stringify(finding.expected_owner_id)};
const PROTECTED_CASES = ${casesJson};
const PUBLIC_CONTROL = ${publicJson};

function requiredEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(name + ' is required');
  return value;
}

async function actorGet(testCase, token) {
  const response = await fetch(BASE_URL + testCase.path, {
    method: testCase.method,
    headers: { authorization: 'Bearer ' + token, accept: 'application/json' },
    redirect: 'error',
    signal: AbortSignal.timeout(5000),
  });
  const raw = await response.text();
  let body = null;
  try { body = JSON.parse(raw); } catch { body = null; }
  return { status: response.status, body };
}

function exposesPrivateOwnerResource(result) {
  return Boolean(
    result.body
    && result.body.kind === PRIVATE_KIND
    && result.body.marker === PRIVATE_MARKER
    && result.body.owner_id === EXPECTED_OWNER
  );
}

for (const testCase of PROTECTED_CASES) {
  test('owner control proves private authority: ' + testCase.id, async () => {
    const owner = await actorGet(testCase, OWNER_TOKEN);
    assert.equal(owner.status, 200);
    assert.equal(exposesPrivateOwnerResource(owner), true);
  });

  test('outsider cannot cross boundary: ' + testCase.id, async () => {
    const outsider = await actorGet(testCase, OUTSIDER_TOKEN);
    assert.equal(
      exposesPrivateOwnerResource(outsider),
      false,
      'outsider received the same semantic private resource as the owner control'
    );
  });
}

test('public route remains a negative control', async () => {
  const owner = await actorGet(PUBLIC_CONTROL, OWNER_TOKEN);
  const outsider = await actorGet(PUBLIC_CONTROL, OUTSIDER_TOKEN);
  assert.equal(owner.status, 200);
  assert.equal(outsider.status, 200);
  assert.equal(exposesPrivateOwnerResource(owner), false);
  assert.equal(exposesPrivateOwnerResource(outsider), false);
});
`;
}

function writeStandaloneTest(outDir, input) {
  const file = path.join(outDir, 'boundary-regression.spec.ts');
  fs.writeFileSync(file, generateStandaloneTest(input), 'utf8');
  return file;
}

module.exports = { generateStandaloneTest, writeStandaloneTest };
