'use strict';

const fs = require('node:fs');
const path = require('node:path');

function generateStandaloneTest({ actors, candidates }) {
  const actorDocument = JSON.stringify(actors, null, 2);
  const cases = JSON.stringify(candidates.map((candidate) => ({
    id: candidate.id,
    route_id: candidate.route_id,
    method: candidate.method,
    path_for_actor_a_resource: candidate.path_for_actor_a_resource,
    path_for_actor_b_resource: candidate.path_for_actor_b_resource,
  })), null, 2);
  return `/* Generated by BOQA Boundary Regression Compiler. No BOQA runtime dependency. */
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const LOOPBACK_BASE_URL_PATTERN = /^http:\\/\\/(?:(127\\.0\\.0\\.1|localhost):([1-9][0-9]{0,4})|\\[::1\\]:([1-9][0-9]{0,4}))\\/?$/;

function requiredEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(name + ' is required');
  return value;
}

function validateLoopbackBaseUrl(baseUrl) {
  if (typeof baseUrl !== 'string' || baseUrl.length === 0 || baseUrl !== baseUrl.trim()) {
    throw new Error('BOQA-005 generated standalone test requires an exact loopback HTTP URL with an explicit port');
  }

  const match = LOOPBACK_BASE_URL_PATTERN.exec(baseUrl);
  if (!match) {
    throw new Error('BOQA-005 generated standalone test is restricted to http://127.0.0.1:<port>, http://localhost:<port>, or http://[::1]:<port>');
  }

  const portText = match[2] || match[3];
  const port = Number(portText);
  if (!Number.isSafeInteger(port) || port < 1 || port > 65535 || String(port) !== portText) {
    throw new Error('BOQA-005 generated standalone loopback port must be canonical and between 1 and 65535');
  }

  const parsed = new URL(baseUrl);
  if (
    parsed.protocol !== 'http:'
    || parsed.username !== ''
    || parsed.password !== ''
    || parsed.pathname !== '/'
    || parsed.search !== ''
    || parsed.hash !== ''
  ) {
    throw new Error('BOQA-005 generated standalone base URL contains a prohibited URL component');
  }

  return baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
}

const BASE_URL = validateLoopbackBaseUrl(requiredEnv('BOUNDARY_BASE_URL'));
const ACTOR_A_TOKEN = requiredEnv('BOQA_ACTOR_A_TOKEN');
const ACTOR_B_TOKEN = requiredEnv('BOQA_ACTOR_B_TOKEN');
const ACTORS = ${actorDocument};
const CASES = ${cases};
const VERDICTS = Object.freeze({
  CONTRADICTED: 'CONTRADICTED',
  NOT_CONTRADICTED: 'NOT_CONTRADICTED_IN_TESTED_SCOPE',
  UNPROVEN: 'UNPROVEN',
  INVALID: 'INVALID_EXPERIMENT',
});

async function actorRequest(testCase, actor, target, token, role) {
  const requestPath = target === 'actor_a' ? testCase.path_for_actor_a_resource : testCase.path_for_actor_b_resource;
  const response = await fetch(BASE_URL + requestPath, {
    method: testCase.method,
    headers: { authorization: 'Bearer ' + token, accept: 'application/json' },
    redirect: 'error',
    signal: AbortSignal.timeout(5000),
  });
  const raw = await response.text();
  let semantic = null;
  try { semantic = JSON.parse(raw); } catch { semantic = null; }
  return { actor, target, role, status: response.status, semantic };
}

function exactInvoice(receipt, expected) {
  const value = receipt && receipt.semantic;
  return Boolean(receipt && receipt.status === 200 && value
    && value.kind === 'private_invoice'
    && value.tenant_id === expected.tenant_id
    && value.user_id === expected.user_id
    && value.account_id === expected.account_id
    && (value.invoice_id === expected.invoice_id || value.resource_id === expected.invoice_id)
    && value.marker === expected.marker);
}

function hasValue(value) {
  if (value === null || value === undefined || value === '') return false;
  if (Array.isArray(value)) return value.length > 0;
  if (typeof value === 'object') return Object.keys(value).length > 0;
  return true;
}

function prohibitedSignals(receipt, expected) {
  const value = receipt && receipt.semantic;
  if (!value || typeof value !== 'object') return [];
  const signals = [];
  if (value.marker === expected.marker) signals.push('owner_marker');
  if (value.invoice_id === expected.invoice_id || value.resource_id === expected.invoice_id) signals.push('invoice_or_resource_id');
  if (value.tenant_id === expected.tenant_id) signals.push('tenant_id');
  if (hasValue(value.sensitive_field) || hasValue(value.sensitive_fields)) signals.push('sensitive_field');
  if (hasValue(value.operational_capability) || hasValue(value.capabilities)) signals.push('operational_capability');
  if (hasValue(value.prohibited_metadata)) signals.push('prohibited_metadata');
  return signals;
}

function evaluate(receipts) {
  if (!exactInvoice(receipts.actor_a_own, ACTORS.actor_a) || !exactInvoice(receipts.actor_b_own, ACTORS.actor_b)) {
    return VERDICTS.INVALID;
  }
  if (prohibitedSignals(receipts.actor_a_cross, ACTORS.actor_b).length > 0
      || prohibitedSignals(receipts.actor_b_cross, ACTORS.actor_a).length > 0) {
    return VERDICTS.CONTRADICTED;
  }
  const definitive = (receipt) => receipt && [401, 403, 404].includes(receipt.status);
  if (definitive(receipts.actor_a_cross) && definitive(receipts.actor_b_cross)) return VERDICTS.NOT_CONTRADICTED;
  return VERDICTS.UNPROVEN;
}

for (const testCase of CASES) {
  test('tenant boundary remains protected: ' + testCase.route_id, async () => {
    const [actorAOwn, actorBOwn, actorACross, actorBCross] = await Promise.all([
      actorRequest(testCase, 'actor_a', 'actor_a', ACTOR_A_TOKEN, 'owner_control'),
      actorRequest(testCase, 'actor_b', 'actor_b', ACTOR_B_TOKEN, 'owner_control'),
      actorRequest(testCase, 'actor_a', 'actor_b', ACTOR_A_TOKEN, 'cross_tenant_probe'),
      actorRequest(testCase, 'actor_b', 'actor_a', ACTOR_B_TOKEN, 'cross_tenant_probe'),
    ]);
    const verdict = evaluate({ actor_a_own: actorAOwn, actor_b_own: actorBOwn, actor_a_cross: actorACross, actor_b_cross: actorBCross });
    assert.equal(verdict, VERDICTS.NOT_CONTRADICTED, 'route did not prove the fixed tenant boundary');
  });
}
`;
}

function writeStandaloneTest(outDir, input) {
  const file = path.join(outDir, 'boundary-regression.spec.ts');
  fs.writeFileSync(file, generateStandaloneTest(input), 'utf8');
  return file;
}

module.exports = { generateStandaloneTest, writeStandaloneTest };
