const {spawnSync,spawn}=require('child_process'),path=require('path'),fs=require('fs');
const LOG_MAX_BYTES=10*1024*1024;
function dockerAvailable(){return spawnSync('docker',['version','--format','{{.Server.Version}}'],{stdio:'ignore',timeout:5000}).status===0;}
function safeHostEnv(){return {PATH:process.env.PATH||'/usr/bin:/bin',HOME:process.env.HOME||'/tmp'};}
function containerArgs(o){if(!Array.isArray(o.args)||o.args.some(a=>typeof a!=='string'))throw new Error('INVALID_ARGV');const uid=process.getuid&&process.getuid()!==0?process.getuid():65534,gid=process.getgid&&process.getgid()!==0?process.getgid():65534;const env=['-e','HOME=/tmp','-e','CI=true'];if(o.playwrightBrowsersPath)env.push('-e',`PLAYWRIGHT_BROWSERS_PATH=${o.playwrightBrowsersPath}`);return ['run','--rm','--name',o.name,'--network',o.network||'none','--user',`${uid}:${gid}`,'--cap-drop','ALL','--security-opt','no-new-privileges','--pids-limit','256','--memory','1g','--cpus','1','--read-only','--tmpfs','/tmp:rw,nosuid,nodev,size=64m',...env,'-v',`${path.resolve(o.targetDir)}:/workspace:rw`,'-v',`${path.resolve(o.outputDir)}:/output:rw`,'-w',o.workdir||'/workspace',o.image,o.executable,...o.args];}
function assertLogBound(stdout='',stderr=''){if(Buffer.byteLength(stdout)>LOG_MAX_BYTES||Buffer.byteLength(stderr)>LOG_MAX_BYTES)throw Object.assign(new Error('LOG_TOO_LARGE'),{code:'LOG_TOO_LARGE'});return true;}
function runDocker(o){if(!(o.allowedExecutables||[]).includes(o.executable))throw Object.assign(new Error('EXECUTABLE_NOT_ALLOWED'),{code:'EXECUTABLE_NOT_ALLOWED'});if(o.network!=='none'&&!o.hydration)throw Object.assign(new Error('NETWORK_POLICY_VIOLATION'),{code:'NETWORK_POLICY_VIOLATION'});if(o.hydration&&o.executable==='npm'&&o.args[0]==='ci'&&!o.args.includes('--ignore-scripts'))throw Object.assign(new Error('LIFECYCLE_SCRIPTS_NOT_DISABLED'),{code:'LIFECYCLE_SCRIPTS_NOT_DISABLED'});if(!dockerAvailable())throw Object.assign(new Error('DOCKER_UNAVAILABLE'),{code:'DOCKER_UNAVAILABLE'});fs.mkdirSync(o.outputDir,{recursive:true});const r=spawnSync('docker',containerArgs(o),{encoding:'utf8',timeout:o.timeoutMs||120000,env:safeHostEnv(),maxBuffer:LOG_MAX_BYTES});if(r.error?.code==='ENOBUFS')throw Object.assign(new Error('LOG_TOO_LARGE'),{code:'LOG_TOO_LARGE'});assertLogBound(r.stdout||'',r.stderr||'');if(r.error?.code==='ETIMEDOUT'){spawnSync('docker',['rm','-f',o.name],{stdio:'ignore',env:safeHostEnv()});return {status:null,timedOut:true,stdout:r.stdout||'',stderr:r.stderr||''};}return {status:r.status,timedOut:false,stdout:r.stdout||'',stderr:r.stderr||''};}
function spawnProcess(exe,args,{cwd,timeoutMs=10000,env={}}={}){return new Promise(resolve=>{const c=spawn(exe,args,{cwd,shell:false,detached:process.platform!=='win32',env:{PATH:process.env.PATH||'',...env},stdio:['ignore','pipe','pipe']});let out='',err='',done=false;const fin=x=>{if(done)return;done=true;clearTimeout(timer);resolve({...x,stdout:out,stderr:err,pid:c.pid});};c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);c.on('exit',(code,signal)=>fin({code,signal,timedOut:false}));const timer=setTimeout(()=>{try{process.kill(-c.pid,'SIGTERM');}catch{}setTimeout(()=>{try{process.kill(-c.pid,'SIGKILL');}catch{}},250).unref();fin({code:null,signal:'SIGTERM',timedOut:true});},timeoutMs);});}
module.exports={LOG_MAX_BYTES,dockerAvailable,safeHostEnv,containerArgs,assertLogBound,runDocker,spawnProcess};
