/* Generated by BOQA Boundary Regression Compiler. No BOQA runtime dependency. */
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const BASE_URL = requiredEnv('BOUNDARY_BASE_URL').replace(/\/$/, '');
const OWNER_TOKEN = requiredEnv('BOUNDARY_OWNER_TOKEN');
const OUTSIDER_TOKEN = requiredEnv('BOUNDARY_OUTSIDER_TOKEN');
const PRIVATE_KIND = "private_project_resource";
const PRIVATE_MARKER = "project-private:project-alpha";
const EXPECTED_OWNER = "owner-alpha";
const PROTECTED_CASES = [
  {
    "id": "seed-project-read",
    "method": "GET",
    "path": "/api/projects/project-alpha",
    "operation": "read"
  },
  {
    "id": "variant-project-audit",
    "method": "GET",
    "path": "/api/projects/project-alpha/audit",
    "operation": "audit"
  },
  {
    "id": "variant-project-export",
    "method": "GET",
    "path": "/api/projects/project-alpha/export",
    "operation": "export"
  }
];
const PUBLIC_CONTROL = {
  "id": "control-project-summary",
  "method": "GET",
  "path": "/api/projects/project-alpha/summary"
};

function requiredEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(name + ' is required');
  return value;
}

async function actorGet(testCase, token) {
  const response = await fetch(BASE_URL + testCase.path, {
    method: testCase.method,
    headers: { authorization: 'Bearer ' + token, accept: 'application/json' },
    redirect: 'error',
    signal: AbortSignal.timeout(5000),
  });
  const raw = await response.text();
  let body = null;
  try { body = JSON.parse(raw); } catch { body = null; }
  return { status: response.status, body };
}

function exposesPrivateOwnerResource(result) {
  return Boolean(
    result.body
    && result.body.kind === PRIVATE_KIND
    && result.body.marker === PRIVATE_MARKER
    && result.body.owner_id === EXPECTED_OWNER
  );
}

for (const testCase of PROTECTED_CASES) {
  test('owner control proves private authority: ' + testCase.id, async () => {
    const owner = await actorGet(testCase, OWNER_TOKEN);
    assert.equal(owner.status, 200);
    assert.equal(exposesPrivateOwnerResource(owner), true);
  });

  test('outsider cannot cross boundary: ' + testCase.id, async () => {
    const outsider = await actorGet(testCase, OUTSIDER_TOKEN);
    assert.equal(
      exposesPrivateOwnerResource(outsider),
      false,
      'outsider received the same semantic private resource as the owner control'
    );
  });
}

test('public route remains a negative control', async () => {
  const owner = await actorGet(PUBLIC_CONTROL, OWNER_TOKEN);
  const outsider = await actorGet(PUBLIC_CONTROL, OUTSIDER_TOKEN);
  assert.equal(owner.status, 200);
  assert.equal(outsider.status, 200);
  assert.equal(exposesPrivateOwnerResource(owner), false);
  assert.equal(exposesPrivateOwnerResource(outsider), false);
});
